version: "3.3"
services:
  postgres:
    image: postgres:14.6-alpine
    container_name: go-rest-boilerplate-postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_ROOT_PASSWORD: dbpass
      POSTGRES_DB: boilerplate
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongo:
    image: bitnami/mongodb:4.4
    container_name: go-rest-boilerplate-mongodb
    restart: always
    volumes:
      - mongo:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo: {}
